export const ACTIVE_FEED = "ACTIVE_FEED";
export const ACTIVE_PROFILE_SETTINGS = "ACTIVE_PROFILE_SETTINGS";
export const ACTIVE_ACCOUNT = "ACTIVE_ACCOUNT";
export const ACTIVE_EXPLORE = "ACTIVE_EXPLORE";
export const ACTIVE_ABOUT = "ACTIVE_ABOUT";
export const ACTIVE_RESET = "ACTIVE_RESET";
