export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
export const UPLOAD_IMAGE_RESET = "UPLOAD_IMAGE_RESET";

export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAIL = "CREATE_STORY_FAIL";
export const CREATE_STORY_RESET = "CREATE_STORY_RESET";

export const STORIES_FETCH_SUCCESS = "STORIES_FETCH_SUCCESS";
export const STORIES_FETCH_FAIL = "STORIES_FETCH_FAIL";

export const STORY_FETCH_SUCCESS = "STORY_FETCH_SUCCESS";
export const STORY_FETCH_FAIL = "STORY_FETCH_FAIL";

export const USER_STORY_FETCH_SUCCESS = "USER_STORY_FETCH_SUCCESS";
export const USER_STORY_FETCH_FAIL = "USER_STORY_FETCH_FAIL";