export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS";
export const USER_VERIFY_FAIL = "USER_VERIFY_FAIL";
export const USER_VERIFY_RESET = "USER_VERIFY_RESET";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_INFO_UPDATE = "USER_INFO_UPDATE";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const RESET = "RESET";

export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const GOOGLE_AUTH_RESET = "GOOGLE_AUTH_RESET";

export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
